// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cefwqunnpfvofpdmiozy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlZndxdW5ucGZ2b2ZwZG1pb3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzUxNjUsImV4cCI6MjA3MjQxMTE2NX0.2HxiGvcLBtrA0VMehLiJjT8VwQagVV3XlDc9zytWBj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});